/* DESIGN-001 data C header: real snapshot 2026-09-14, UTF-8 verbatim. */
window.__D001_DATA = window.__D001_DATA || {};
window.__D001_DATA.stories = [
  { slug: "01-gioi-thieu",
    title: "Giới Thiệu: MẠCH được bắt đầu như thế nào?",
    subtitle: "Khởi đầu của hành trình tìm lại những mạch nối gia đình.",
    dek: "Dòng họ trong đời sống đương đại đang đứng trước một sự chuyển dịch âm thầm nhưng sâu sắc.",
    date: "2026-07-03T16:38:00+07:00",
    series: "issue-01",
    cover: "https://api.giatoctrantrongthu.com/assets/images/mach/issue-01/mach_01.jpg" },
  { slug: "02-cay-gia-pha-va-mach",
    title: "Cây Gia Phả & Mạch",
    dek: "Cây gia phả lưu lại cấu trúc và vị trí. MẠCH lưu lại những gì xảy ra giữa những vị trí ấy.",
    date: "2026-07-03T16:38:00+07:00",
    series: "issue-01",
    cover: "" },
  { slug: "03-khi-su-gan-gui-khong-con-tu-nhien",
    title: "Khi Sự Gần Gũi Không Còn TỰ NHIÊN",
    dek: "Có những người lớn lên trong việc đi vài căn nhà là tới nhà họ hàng. Nhưng theo thời gian, sự gần gũi tự nhiên ấy dần trở nên mong manh.",
    date: "2026-07-03T16:38:00+07:00",
    series: "issue-01",
    cover: "" },
  { slug: "04-tu-he-tu-tuong-den-dao-ly-doi-song",
    title: "Từ Hệ Tư Tưởng Đến Đạo Lý Đời SỐNG",
    dek: "Những triết lý lớn khi đi vào nếp nhà thường co lại thành vài câu giản dị nhưng đủ sức giữ trật tự qua nhiều biến động.",
    date: "2026-07-03T16:38:00+07:00",
    series: "issue-01",
    cover: "" },
  { slug: "05-nhung-khe-uoc-vo-hinh-cua-dong-ho",
    title: "Những Khế Ước Vô Hình Của Dòng Họ",
    dek: "Có những trách nhiệm trong họ không bao giờ được viết thành văn, nhưng mọi người đều ngầm hiểu và tuân thủ.",
    date: "2026-07-03T16:38:00+07:00",
    series: "issue-01",
    cover: "" }
];
